[
  {
    description: "batsman",
    from: "CSK",
    id: "1",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "MS Dhoni",
    price: "10",
    teamImage: "https://wallpaperaccess.com/full/1898247.jpg",
  },
  {
    description: "bowler",
    from: "CSK",
    id: "2",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "Imran Tahir",
    price: "10",
    teamImage: "https://wallpaperaccess.com/full/1898247.jpg",
  },
  {
    description: "batsman",
    from: "CSK",
    id: "3",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "Suresh Raina",
    price: "10",
    teamImage: "https://wallpaperaccess.com/full/1898247.jpg",
  },
  {
    description: "batsman",
    from: "CSK",
    id: "4",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "Dwayne Bravo",
    price: "10",
    teamImage: "https://wallpaperaccess.com/full/1898247.jpg",
  },
  {
    description: "batsman",
    from: "MI",
    id: "5",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "Suresh Raina",
    price: "10",
    teamImage:
      "https://d28wu8o6itv89t.cloudfront.net/images/MumbaiIndianspng-1598599799716.png",
  },
  {
    description: "batsman",
    from: "MI",
    id: "6",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "Dwayne Bravo",
    price: "10",
    teamImage:
      "https://d28wu8o6itv89t.cloudfront.net/images/MumbaiIndianspng-1598599799716.png",
  },
  {
    description: "batsman",
    from: "RCB",
    id: "7",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "Suresh Raina",
    price: "10",
    teamImage:
      "https://images.outlookindia.com/public/uploads/articles/2020/2/14/RCB-Logo_571_855.jpg",
  },
  {
    description: "batsman",
    from: "RCB",
    id: "8",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "Dwayne Bravo",
    price: "10",
    teamImage:
      "https://images.outlookindia.com/public/uploads/articles/2020/2/14/RCB-Logo_571_855.jpg",
  },
  {
    description: "batsman",
    from: "RR",
    id: "9",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "Suresh Raina",
    price: "10",
    teamImage:
      "https://i.pinimg.com/originals/2e/80/64/2e806426a58732ebe889e32970aecbb7.jpg",
  },
  {
    description: "batsman",
    from: "RR",
    id: "10",
    imageUrl: "https://static.iplt20.com/players/210/1.png",
    isPlaying: "true",
    playerName: "Dwayne Bravo",
    price: "10",
    teamImage:
      "https://i.pinimg.com/originals/2e/80/64/2e806426a58732ebe889e32970aecbb7.jpg",
  },
];
